### ISSUE TITLE
New User Form

### ISSUE THREAD

**Issue by gdeamicis** [ivanvgav/txtjs#9]
As a User I would like to have a New User Form, where I can input my email, my username, and my password, in order to create a new User.

The following validations should be done by the form:

- [x] Email: should be a valid email
- [x] Username: should have 6-30 characters
- [x] Password: should have a minimum of 8 characters. Must include one lower case, one upper case, one number and one special character. It should be inputted twice. Both password inputted should be the same in order to save the user.

The Form should show one back button, to go back to the Login Form, and one Create User button, to finalise the creation of the User.

**Comment by gdeamicis** [comment]
When clicking on the Create User button:

- [x] If the form is valid, I should be redirected to the Login Form, and an alert that the User was created successfully should be shown, showing the User data.
- [x] If there is any error during the User Creation, I should be shown an alert stating that an Error has occurred, and that the User should try again later.

**Comment by ivanvgav** [comment]
I'm having some problem to store into localStorege the variables.
When I try to push by submit the web page it gives at first error 405, then I try to fix it, but the data do not store, only appear as `undefinied`.
